# coding: utf-8

"""
    Drones Test Exercise API

    This is a sample API for renting time on a drones-as-a-service platform.  # noqa: E501

    OpenAPI spec version: 1.1.0
    Contact: info@superorbital.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.models_drone import ModelsDrone  # noqa: E501
from swagger_client.rest import ApiException


class TestModelsDrone(unittest.TestCase):
    """ModelsDrone unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelsDrone(self):
        """Test ModelsDrone"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.models_drone.ModelsDrone()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
