# coding: utf-8

# flake8: noqa

"""
    Drones Test Exercise API

    This is a sample API for renting time on a drones-as-a-service platform.  # noqa: E501

    OpenAPI spec version: 1.1.0
    Contact: info@superorbital.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.drone_api import DroneApi
# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.models_drone import ModelsDrone
from swagger_client.models.models_drone_cost import ModelsDroneCost
